const D=window.ROADMAP_DATA; const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
const navItems=[['overview','⌂','Overview'],['path','⇢','Learning Path'],['courses','▦','Course Library'],['skills','✦','Core Skills'],['projects','◈','Project Ladder'],['glossary','A–Z','Glossary']];
let current='overview';
function done(){try{return JSON.parse(localStorage.getItem('ai-roadmap-progress')||'[]')}catch{return[]}} function setDone(x){localStorage.setItem('ai-roadmap-progress',JSON.stringify(x));updateProgress();renderCurrent()} function toggleDone(id){let d=done();setDone(d.includes(id)?d.filter(x=>x!==id):[...d,id])} function isDone(id){return done().includes(id)}
function pill(s,cls=''){return `<span class="pill ${cls}" title="Skill ${s}">${s}</span>`} function esc(s){return String(s).replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
function levelClass(l){return l.includes('Advanced')?'advanced':l.includes('Intermediate')?'intermediate':'beginner'}
function updateProgress(){let n=done().length,p=Math.round(n/D.courses.length*100);$('#progressPct').textContent=p+'%';$('#progressCount').textContent=n;$('#progressBar').style.width=p+'%'}
function buildNav(){ $('#nav').innerHTML=navItems.map(([id,icon,label])=>`<button data-nav="${id}"><span style="display:inline-block;width:28px">${icon}</span>${label}</button>`).join(''); $$('[data-nav]').forEach(b=>b.onclick=()=>show(b.dataset.nav)); }
function show(id){current=id;$$('.page').forEach(p=>p.classList.toggle('active',p.dataset.page===id));$$('[data-nav]').forEach(b=>b.classList.toggle('active',b.dataset.nav===id));renderCurrent();window.scrollTo(0,0);$('#sidebar').classList.remove('open');$('#backdrop').classList.remove('show')}
function renderCurrent(){({overview:renderOverview,path:renderPath,courses:renderCourses,skills:renderSkills,projects:renderProjects,glossary:renderGlossary}[current]||(()=>{}))();updateProgress()}
function renderOverview(){let n=done().length,p=Math.round(n/D.courses.length*100); $('#page-overview').innerHTML=`
<div class="hero"><div class="eyebrow">Complete AI literacy roadmap</div><h1>AI User → Power User → Builder → Systems Thinker</h1><p>Learn not only how to talk to AI, but how modern AI systems actually fit together: prompting, context, APIs, databases, SaaS, automation, RAG, MCP, agents, coding, cloud, security, and production thinking.</p><div class="hero-actions"><button class="btn primary" onclick="show('path')">Start the learning path →</button><button class="btn secondary" onclick="show('courses')">Browse all 30 resources</button></div></div>
<div class="section-head"><div><h2>Your progression</h2><p>${n} of ${D.courses.length} resources complete · ${p}% overall</p></div></div>
<div class="grid four">${[['AI-literate','Collaborate with AI and review its work.','Levels 1'],['AI power user','Engineer context, research, and workflows.','Levels 1–2'],['AI-native builder','Build with APIs, data, RAG, MCP, agents and cloud.','Levels 3–10'],['AI systems thinker','Design boundaries between AI, software, data and humans.','Levels 11–12']].map((x,i)=>`<div class="card stage-card"><span class="stage-num">0${i+1}</span><h3>${x[0]}</h3><p>${x[1]}</p><div style="margin-top:14px;color:var(--primary);font-size:12px;font-weight:700">${x[2]}</div></div>`).join('')}</div>
<div class="section-head"><div><h2>12 levels at a glance</h2><p>Go in order, but build something at every stage.</p></div><button class="btn outline" onclick="show('path')">Open full path</button></div>
<div class="grid three">${D.stages.map(s=>`<div class="card"><span class="stage-num">Level ${s.level}</span><h3>${s.title}</h3><p>${s.summary}</p><div class="skill-pills" style="margin-top:13px">${s.skills.map(pill).join('')}</div></div>`).join('')}</div>`}
function renderPath(){let course=id=>D.courses.find(c=>c.id===id);$('#page-path').innerHTML=`<div class="page-title"><h1>Learning Path</h1><p>A practical sequence from beginner fundamentals to production-grade AI systems thinking.</p></div><div class="roadmap-line">${D.stages.map(s=>`<div class="level-block"><div class="level-header"><div class="level-badge">${s.level}</div><div><h3>${s.title}</h3><p>${s.summary}</p><div class="skill-pills" style="margin-top:10px">${s.skills.map(pill).join('')}</div></div></div>${s.courses.length?`<div class="level-courses">${s.courses.map(id=>{let c=course(id);return `<div class="mini-course"><input class="check" type="checkbox" ${isDone(id)?'checked':''} onchange="toggleDone(${id})"><div class="meta"><strong>${esc(c.title)}</strong><span>${esc(c.provider)} · ${esc(c.time)} · ${esc(c.level)}</span></div><a class="btn outline" href="${c.url}" target="_blank" rel="noopener">Open ↗</a></div>`}).join('')}</div>`:''}${s.practice?`<div class="practice"><strong>Practice:</strong> ${esc(s.practice)}</div>`:''}</div>`).join('')}</div>`}
function courseCard(c){return `<article class="card course-card"><div class="course-top"><div><div class="course-num">RESOURCE ${String(c.id).padStart(2,'0')}</div><h3>${esc(c.title)}</h3><div class="course-provider">${esc(c.provider)}</div></div><span class="pill ${levelClass(c.level)}">${esc(c.level)}</span></div><div class="course-meta"><span class="meta-chip">⏱ ${esc(c.time)}</span><span class="meta-chip">${esc(c.access)}</span></div><div class="course-desc">${esc(c.description)}</div>${c.why?`<div class="why"><strong>Why it matters:</strong> ${esc(c.why)}</div>`:''}<div class="tags">${c.skills.map(pill).join('')}</div><div class="course-actions"><label class="done-label"><input class="check" type="checkbox" ${isDone(c.id)?'checked':''} onchange="toggleDone(${c.id})"> Completed</label><a class="btn link" href="${c.url}" target="_blank" rel="noopener">Open resource ↗</a></div></article>`}
function renderCourses(){let providers=[...new Set(D.courses.map(c=>c.provider))].sort();$('#page-courses').innerHTML=`<div class="page-title"><h1>Course Library</h1><p>All ${D.courses.length} curated resources. Links reviewed ${D.reviewed}.</p></div><div class="controls"><input id="courseSearch" placeholder="Search title, provider, skill, or description…"><select id="levelFilter"><option value="">All levels</option><option>Beginner</option><option>Intermediate</option><option>Advanced</option></select><select id="providerFilter"><option value="">All providers</option>${providers.map(p=>`<option>${esc(p)}</option>`).join('')}</select><select id="accessFilter"><option value="">All access</option><option value="free">Free / free learning</option><option value="paidapi">API may cost</option></select><select id="sortFilter"><option value="order">Roadmap order</option><option value="beginner">Beginner first</option><option value="title">A–Z</option></select></div><div id="courseResults" class="course-grid"></div>`;['courseSearch','levelFilter','providerFilter','accessFilter','sortFilter'].forEach(id=>$('#'+id).oninput=filterCourses);filterCourses()}
function filterCourses(){let q=($('#courseSearch')?.value||'').toLowerCase(),lv=$('#levelFilter')?.value||'',pr=$('#providerFilter')?.value||'',ac=$('#accessFilter')?.value||'',sort=$('#sortFilter')?.value||'order';let x=D.courses.filter(c=>(!q||[c.title,c.provider,c.description,c.skills.join(' ')].join(' ').toLowerCase().includes(q))&&(!lv||c.level.includes(lv))&&(!pr||c.provider===pr)&&(!ac||(ac==='free'?c.access.toLowerCase().includes('free'):c.access.toLowerCase().includes('api usage paid'))));if(sort==='title')x.sort((a,b)=>a.title.localeCompare(b.title));if(sort==='beginner')x.sort((a,b)=>levelClass(a.level).localeCompare(levelClass(b.level)));$('#courseResults').innerHTML=x.length?x.map(courseCard).join(''):'<div class="empty">No resources match those filters.</div>'}
function renderSkills(){let groups=[...new Set(D.skills.map(s=>s.group))];$('#page-skills').innerHTML=`<div class="page-title"><h1>Core Skills Map</h1><p>Every concept from A–AH, grouped by domain. Click a card to see resources that teach it.</p></div>${groups.map(g=>`<div class="skill-group"><h2>${g}</h2><div class="skill-grid">${D.skills.filter(s=>s.group===g).map(s=>{let cs=D.courses.filter(c=>c.skills.includes(s.code));return `<div class="card skill-card" onclick="this.classList.toggle('open')"><div class="skill-title"><span class="skill-code">${s.code}</span><div><h3>${esc(s.name)}</h3><p>${esc(s.summary)}</p></div></div><div class="why-small"><strong>Why it matters:</strong> ${esc(s.why)}</div><div class="skill-courses"><strong>Resources teaching this:</strong>${cs.length?cs.map(c=>`<a href="${c.url}" target="_blank" rel="noopener" onclick="event.stopPropagation()">${c.id}. ${esc(c.title)} ↗</a>`).join(''):'<p style="margin-top:8px">Covered through practice/project work.</p>'}</div></div>`}).join('')}</div></div>`).join('')}`}
function renderProjects(){$('#page-projects').innerHTML=`<div class="page-title"><h1>Project Ladder</h1><p>Do not wait until the end to build. Each project makes the next layer of the roadmap concrete.</p></div><div class="project-ladder">${D.projects.map(p=>`<div class="project"><div class="project-step">${p.id}</div><div class="card project-card"><h3>${esc(p.title)}</h3><div class="project-focus">${esc(p.focus)}</div><p>${esc(p.description)}</p><div class="skill-pills" style="margin-top:12px">${p.skills.map(pill).join('')}</div><div class="after-level">Best attempted after Level ${p.after}</div></div></div>`).join('')}</div>`}
function renderGlossary(){$('#page-glossary').innerHTML=`<div class="page-title"><h1>Glossary</h1><p>Plain-language definitions for the vocabulary you will meet throughout the roadmap.</p></div><div class="controls"><input id="glossSearch" placeholder="Search API, OAuth, RAG, MCP, embeddings…"></div><div id="glossResults" class="glossary-list"></div>`;$('#glossSearch').oninput=filterGlossary;filterGlossary()}
function filterGlossary(){let q=($('#glossSearch')?.value||'').toLowerCase();let e=Object.entries(D.glossary).filter(([t,d])=>!q||(t+' '+d).toLowerCase().includes(q)).sort((a,b)=>a[0].localeCompare(b[0]));$('#glossResults').innerHTML=e.length?e.map(([t,d])=>`<div class="glossary-item"><h3>${esc(t)}</h3><p>${esc(d)}</p></div>`).join(''):'<div class="empty">No glossary entries match that search.</div>'}
function toggleTheme(){document.body.classList.toggle('dark');localStorage.setItem('ai-roadmap-theme',document.body.classList.contains('dark')?'dark':'light');syncTheme()} function syncTheme(){let dark=document.body.classList.contains('dark');$('#themeBtn').textContent=dark?'☀ Light mode':'☾ Dark mode';$('#mobileThemeBtn').textContent=dark?'☀':'☾'}
function init(){if(localStorage.getItem('ai-roadmap-theme')==='dark'||(!localStorage.getItem('ai-roadmap-theme')&&matchMedia('(prefers-color-scheme: dark)').matches))document.body.classList.add('dark');buildNav();$('#themeBtn').onclick=toggleTheme;$('#mobileThemeBtn').onclick=toggleTheme;$('#menuBtn').onclick=()=>{$('#sidebar').classList.add('open');$('#backdrop').classList.add('show')};$('#backdrop').onclick=()=>{$('#sidebar').classList.remove('open');$('#backdrop').classList.remove('show')};$('#resetBtn').onclick=()=>{if(confirm('Reset all course completion progress?'))setDone([])};syncTheme();show('overview')}
init();
